server:
  port: 4321

spring:
  profiles:
    active: default

  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    url: jdbc:mysql://localhost:3306
    schemas: order
    user: root
    password: pass
    locations: classpath:db/migration
    validate-on-migrate: true

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "/system/health"
      exposure:
        include: "*"